version: '3.8'

services:
    db-account:
        image: mysql:8.0.32
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: leapeHxTWGsesRC00lJn
            MYSQL_USER: admin
            MYSQL_PASSWORD: leapeHxTWGsesRC00lJn
            MYSQL_DATABASE: account
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
        ports:
            - 44557:3306
        volumes:
            - ../../../../db-account/conf.d:/etc/mysql/conf.d
            - ../../../../db-account/data:/var/lib/mysql
            - ../../../../db-account/initdb.d:/docker-entrypoint-initdb.d    