version: '3.8'

services:
    db-movie:
        image: mysql:8.0.32
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: leapeHxTWGsesRC00lJn
            MYSQL_USER: admin
            MYSQL_PASSWORD: leapeHxTWGsesRC00lJn
            MYSQL_DATABASE: movie
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
        ports:
            - 44558:3306
        volumes:
            - ../../../../db-movie/conf.d:/etc/mysql/conf.d
            - ../../../../db-movie/data:/var/lib/mysql
            - ../../../../db-movie/initdb.d:/docker-entrypoint-initdb.d    